<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Copyright>2026</Copyright>
    <Authors>Ahmed Yasin Koculu, Blake Pell</Authors>
    <PackageId>Mosaic.UI.Scripting</PackageId>
    <Title>Mosaic.UI.Scripting</Title>
    <ProductVersion>2026.10.4.1</ProductVersion>
    <Version>2026.10.4.1</Version>
    <AssemblyTitle>Mosaic.UI.Scripting</AssemblyTitle>
    <Description>Multithreaded Extended Javascript Engine for .NET</Description>
    <Summmary>Customizable Javascript Engine for use with MosaicUIWpf.</Summmary>
    <PackageTags>mosaic, javascript, engine, interpreter, es5, es2015, es6, ecmascript, interop</PackageTags>

    <PackageProjectUrl>https://github.com/blakepell/MosaicUIWpf</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <DebugType>portable</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
