<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en-US</NeutralLanguage>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RepositoryUrl>https://github.com/blakepell/MosaicUIWpf</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <LangVersion>11.0</LangVersion>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <RepositoryType>git</RepositoryType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <RootNamespace>Mosaic.UI.Scripting</RootNamespace>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <AnalysisMode>All</AnalysisMode>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>C:\Git\MosaicUIWpf\src\Mosaic.Scripting\Mosaic.UI.Scripting.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Docs\Application-Objects.md" />
    <None Remove="Docs\Arrays-and-Objects.md" />
    <None Remove="Docs\Compatibility.md" />
    <None Remove="Docs\Control-Flow.md" />
    <None Remove="Docs\Errors-and-Async.md" />
    <None Remove="Docs\Functions.md" />
    <None Remove="Docs\Getting-Started.md" />
    <None Remove="Docs\Include.md" />
    <None Remove="Docs\LINQ.md" />
    <None Remove="Docs\README.md" />
    <None Remove="Docs\Recipes.md" />
    <None Remove="Docs\Variables-and-Operators.md" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Esprima\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\3rdParty\</PackagePath>
    </None>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Docs\Application-Objects.md" />
    <Resource Include="Docs\Arrays-and-Objects.md" />
    <Resource Include="Docs\Compatibility.md" />
    <Resource Include="Docs\Control-Flow.md" />
    <Resource Include="Docs\Errors-and-Async.md" />
    <Resource Include="Docs\Functions.md" />
    <Resource Include="Docs\Getting-Started.md" />
    <Resource Include="Docs\Include.md" />
    <Resource Include="Docs\LINQ.md" />
    <Resource Include="Docs\README.md" />
    <Resource Include="Docs\Recipes.md" />
    <Resource Include="Docs\Variables-and-Operators.md" />
  </ItemGroup>

</Project>
