//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace AvalonDock.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("AvalonDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Files.
        /// </summary>
        public static string Active_Files {
            get {
                return ResourceManager.GetString("Active_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Tool Windows.
        /// </summary>
        public static string Active_ToolWindows {
            get {
                return ResourceManager.GetString("Active_ToolWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        public static string Anchorable_AutoHide {
            get {
                return ResourceManager.GetString("Anchorable_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        public static string Anchorable_BtnAutoHide_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnAutoHide_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Anchorable_BtnClose_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnClose_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        public static string Anchorable_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Anchorable_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string Anchorable_Dock {
            get {
                return ResourceManager.GetString("Anchorable_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document.
        /// </summary>
        public static string Anchorable_DockAsDocument {
            get {
                return ResourceManager.GetString("Anchorable_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string Anchorable_Float {
            get {
                return ResourceManager.GetString("Anchorable_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Anchorable_Hide {
            get {
                return ResourceManager.GetString("Anchorable_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Pin status.
        /// </summary>
        public static string Document_BtnPinned_Hint {
            get {
                return ResourceManager.GetString("Document_BtnPinned_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Document_Close {
            get {
                return ResourceManager.GetString("Document_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string Document_CloseAll {
            get {
                return ResourceManager.GetString("Document_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string Document_CloseAllButThis {
            get {
                return ResourceManager.GetString("Document_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        public static string Document_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Document_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document.
        /// </summary>
        public static string Document_DockAsDocument {
            get {
                return ResourceManager.GetString("Document_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string Document_Float {
            get {
                return ResourceManager.GetString("Document_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Next Tab Group.
        /// </summary>
        public static string Document_MoveToNextTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToNextTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Previous Tab Group.
        /// </summary>
        public static string Document_MoveToPreviousTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToPreviousTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Horizontal Tab Group.
        /// </summary>
        public static string Document_NewHorizontalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewHorizontalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vertical Tab Group.
        /// </summary>
        public static string Document_NewVerticalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewVerticalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Window_Maximize {
            get {
                return ResourceManager.GetString("Window_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Window_Restore {
            get {
                return ResourceManager.GetString("Window_Restore", resourceCulture);
            }
        }
    }
}
