/*
 * Mosaic UI for WPF
 *
 * @project lead      : Blake Pell
 * @website           : https://www.blakepell.com
 * @website           : https://www.apexgate.net
 * @copyright         : Copyright (c), 2023-2026 All rights reserved.
 * @license           : MIT - https://opensource.org/license/mit/
 */

// ReSharper disable CheckNamespace

namespace Mosaic.UI.Wpf.Controls
{
    /// <summary>
    /// An immutable item generated by <see cref="EnumComboBox"/> that pairs a declared enum
    /// value with its friendly display name.
    /// </summary>
    /// <remarks>
    /// The display name is resolved from the enum field's <see cref="DisplayNameAttribute"/> when
    /// present, then its <see cref="DescriptionAttribute"/>, and finally falls back to the enum
    /// member name itself.
    /// </remarks>
    public sealed class EnumComboBoxItem
    {
        /// <summary>
        /// Initializes a new instance of <see cref="EnumComboBoxItem"/>.
        /// </summary>
        /// <param name="value">The actual enum value this item represents.</param>
        /// <param name="displayName">The friendly display name shown to the user.</param>
        public EnumComboBoxItem(object value, string displayName)
        {
            Value = value;
            DisplayName = displayName;
        }

        /// <summary>
        /// Gets the actual enum value this item represents.  This is the value surfaced through
        /// <see cref="System.Windows.Controls.Primitives.Selector.SelectedValue"/> on the owning
        /// <see cref="EnumComboBox"/>.
        /// </summary>
        public object Value { get; }

        /// <summary>
        /// Gets the friendly display name shown in the drop-down for this enum value.
        /// </summary>
        public string DisplayName { get; }

        /// <summary>
        /// Returns the <see cref="DisplayName"/> for this item.
        /// </summary>
        public override string ToString() => DisplayName;
    }
}
